### ISSUE TITLE
Weights of the keras model

### ISSUE THREAD

**Issue by dsiervo** [jimmy60504/SeisNN#4]
Hi Jimmy, I can't find the weights of the keras model in the repository. Can you share the weights (or the entire model) of the Keras version of PhaseNet that could be loaded into SeisNN?

The idea is to do fine-tuning for aftershock picking. Thanks for your attention.

**Comment by jimmy60504** [comment]
The weight is not available for external use now.

One of the reason is we did not use the same model with PhaseNet by the way. (Unet++ vs. Unet)

The other reason is the data which trained the weight is come from our lab, we did not decide how to distribute the weight and other restrictions yet. 

So in this period, you need to train on your data. Or you can try using the data which is available on the internet.

Thank you for your interest. We will update soon.

**Comment by dsiervo** [comment]
Thanks for your reply, it is completely understandable. I will watch for the update.
